services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - ./var/db:/var/lib/postgresql/data
    ports:
      - "${DB_SETTINGS__PORT:-5435}:5432"
    environment:
      - POSTGRES_USER=${DB_SETTINGS__USER:-postgres}
      - POSTGRES_PASSWORD=${DB_SETTINGS__PASSWORD:-postgres}
      - POSTGRES_DB=${DB_SETTINGS__NAME:-edumaster}
    

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_SETTINGS__USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_SETTINGS__PASSWORD:-minio_pwd}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_SETTINGS__PORT:-5672}:5672"
      - "15672:15672"
    volumes:
      - ~/rabbitmq/data:/var/lib/rabbitmq
      - ~/rabbitmq/logs:/var/log/rabbitmq
    depends_on:
      - postgres


  app:
    build: .
    command: python3 -m app.main
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - minio
    environment:
      - RUNNING_IN_DOCKER=true
      - DB_SETTINGS__PORT=${DB_SETTINGS__PORT_DOCKER:-5432}
      - DB_SETTINGS__USER=${DB_SETTINGS__USER:-postgres}
      - DB_SETTINGS__HOST=${DB_SETTINGS__HOST:-postgres}
      - DB_SETTINGS__PASSWORD=${DB_SETTINGS__PASSWORD:-postgres}
      - DB_SETTINGS__NAME=${DB_SETTINGS__NAME:-edumaster}
      - MINIO_SETTINGS__PORT=9000
      - RABBITMQ_SETTINGS__PORT=5672
  
  payment_consumer:
    build: .
    command: python3 -m app.consumers.payment_consumer
    env_file:
      - ./.env
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - RUNNING_IN_DOCKER=true
      - PYTHONUNBUFFERED=1
      - RABBITMQ_SETTINGS__PORT=5672
      