"""PaymentTransaction rename transaction_id 

Revision ID: 0d545a3f3f61
Revises: a6a8d809cefe
Create Date: 2025-07-07 12:05:20.443657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d545a3f3f61'
down_revision: Union[str, None] = 'a6a8d809cefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('transaction_uuid', sa.Uuid(as_uuid=False), nullable=False))
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_index('ix_payment_transactions_transaction_id', table_name='payment_transactions')
    op.create_index(op.f('ix_payment_transactions_transaction_uuid'), 'payment_transactions', ['transaction_uuid'], unique=True)
    op.drop_column('payment_transactions', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_payment_transactions_transaction_uuid'), table_name='payment_transactions')
    op.create_index('ix_payment_transactions_transaction_id', 'payment_transactions', ['transaction_id'], unique=True)
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('payment_transactions', 'transaction_uuid')
    # ### end Alembic commands ###
