"""added payment_intent_id field in PaymentTransaction

Revision ID: 2eff2b328871
Revises: 65504507b45c
Create Date: 2025-07-12 17:30:40.503390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eff2b328871'
down_revision: Union[str, None] = '65504507b45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('payment_intent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'payment_intent_id')
    # ### end Alembic commands ###
