"""minor changes

Revision ID: 2f0604a48143
Revises: cc1fed24ebaf
Create Date: 2025-07-06 22:18:20.666963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0604a48143'
down_revision: Union[str, None] = 'cc1fed24ebaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_purchases', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('course_purchases', sa.Column('course_id', sa.Integer(), nullable=False))
    op.add_column('course_purchases', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_course_purchases_course_id_courses'), 'course_purchases', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('fk_course_purchases_user_id_users'), 'course_purchases', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_course_purchases_transaction_id_payment_transactions'), 'course_purchases', 'payment_transactions', ['transaction_id'], ['id'])
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_course_purchases_transaction_id_payment_transactions'), 'course_purchases', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_purchases_user_id_users'), 'course_purchases', type_='foreignkey')
    op.drop_constraint(op.f('fk_course_purchases_course_id_courses'), 'course_purchases', type_='foreignkey')
    op.drop_column('course_purchases', 'transaction_id')
    op.drop_column('course_purchases', 'course_id')
    op.drop_column('course_purchases', 'user_id')
    # ### end Alembic commands ###
