"""removed user_email from PaymentTransaction

Revision ID: 65504507b45c
Revises: e5b6666492b4
Create Date: 2025-07-07 12:33:13.433267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65504507b45c'
down_revision: Union[str, None] = 'e5b6666492b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
