"""deleted is_archived fields in Lensson, Module

Revision ID: 9f0238c211df
Revises: b29dbd7d40ad
Create Date: 2025-05-27 15:26:53.037284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0238c211df'
down_revision: Union[str, None] = 'b29dbd7d40ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_blocks', 'is_archived')
    op.drop_column('modules', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lesson_blocks', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
