"""added tables module and lesson

Revision ID: a3db3dfcdcbd
Revises: 585392a27761
Create Date: 2025-05-22 10:59:21.820383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3db3dfcdcbd'
down_revision: Union[str, None] = '585392a27761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course', sa.Column('enrolled_at', sa.DateTime(), nullable=False))
    op.add_column('user_course', sa.Column('progress', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course', 'progress')
    op.drop_column('user_course', 'enrolled_at')
    # ### end Alembic commands ###
