"""PaymentTransaction fixes

Revision ID: a6a8d809cefe
Revises: ddd3d86d83df
Create Date: 2025-07-07 11:50:10.556045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a8d809cefe'
down_revision: Union[str, None] = 'ddd3d86d83df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('course_purchase_id', sa.Integer(), nullable=False))
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_payment_transactions_course_id_courses'), 'payment_transactions', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(op.f('fk_payment_transactions_course_purchase_id_course_purchases'), 'payment_transactions', 'course_purchases', ['course_purchase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_payment_transactions_course_purchase_id_course_purchases'), 'payment_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_payment_transactions_course_id_courses'), 'payment_transactions', type_='foreignkey')
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('payment_transactions', 'course_purchase_id')
    # ### end Alembic commands ###
