"""added status field to Lesson, Course, Module

Revision ID: b29dbd7d40ad
Revises: 6fcc0cf9d916
Create Date: 2025-05-27 15:20:58.245276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29dbd7d40ad'
down_revision: Union[str, None] = '6fcc0cf9d916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('status', sa.Enum('draft', 'published', 'archived', name='course_status_enum'), server_default='draft', nullable=False))
    op.add_column('modules', sa.Column('status', sa.Enum('draft', 'published', 'archived', name='course_status_enum'), server_default='draft', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'status')
    op.drop_column('lessons', 'status')
    # ### end Alembic commands ###
