"""create content_type field in Module

Revision ID: d838cb48856d
Revises: 9f0238c211df
Create Date: 2025-06-01 12:43:01.443583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd838cb48856d'
down_revision: Union[str, None] = '9f0238c211df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    content_type_enum = postgresql.ENUM('empty', 'modules', 'lessons', name='content_type_enum')
    content_type_enum.create(op.get_bind())
    op.add_column('modules', sa.Column('content_type', content_type_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'content_type')
    content_type_enum = postgresql.ENUM('empty', 'modules', 'lessons', name='content_type_enum')
    content_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
