"""PaymentTransaction fixes

Revision ID: ddd3d86d83df
Revises: 2f0604a48143
Create Date: 2025-07-07 11:29:40.218238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd3d86d83df'
down_revision: Union[str, None] = '2f0604a48143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_payment_transactions_user_id_users'), 'payment_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_payment_transactions_user_id_users'), 'payment_transactions', type_='foreignkey')
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('payment_transactions', 'user_id')
    # ### end Alembic commands ###
