"""created course_id field in Lesson

Revision ID: e99d82a774a7
Revises: d838cb48856d
Create Date: 2025-06-01 14:48:51.040751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99d82a774a7'
down_revision: Union[str, None] = 'd838cb48856d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_lessons_course_id_courses'), 'lessons', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_lessons_course_id_courses'), 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'course_id')
    # ### end Alembic commands ###
