"""Lesson field module_id nullable=True

Revision ID: eed2e9ebf6ed
Revises: e99d82a774a7
Create Date: 2025-06-04 18:24:21.032018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed2e9ebf6ed'
down_revision: Union[str, None] = 'e99d82a774a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
