"""removed course_purchase_id in PaymentTransaction

Revision ID: fa23906140b7
Revises: 3a19f2f447a0
Create Date: 2025-07-07 12:25:14.330658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa23906140b7'
down_revision: Union[str, None] = '3a19f2f447a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_course_purchases_transaction_id'), 'course_purchases', ['transaction_id'])
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_constraint('fk_payment_transactions_course_purchase_id_course_purchases', 'payment_transactions', type_='foreignkey')
    op.drop_column('payment_transactions', 'course_purchase_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('course_purchase_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_payment_transactions_course_purchase_id_course_purchases', 'payment_transactions', 'course_purchases', ['course_purchase_id'], ['id'])
    op.alter_column('payment_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_course_purchases_transaction_id'), 'course_purchases', type_='unique')
    # ### end Alembic commands ###
